### PR TITLE
[SKCP-102] Add method for retrieving team's list of Slack channels.

### PR DESCRIPTION
**Pull request by pinkie1378**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/InternationalMixMob/CSCI-E-71_IMM_Slacker_Client_Android/pull/6" target="_blank">ReviewNinja

**Comment by jsanford8** [comment]
Shouldn't we also add the method to the interface first? Otherwise it looks good to me.

**Comment by pinkie1378** [comment]
Which method? `getChannelList` is in the interface.

**Comment by jsanford8** [comment]
Whoops, you're right, sorry

**Pull request merged**
